apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-portal-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-portal
  template:
    metadata:
      labels:
        app: student-portal
    spec:
      containers:
      - name: student-portal
        image: yourdockerhubusername/studentprojectportal:latest
        ports:
        - containerPort: 5000
